services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    ports:
      - "4000:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "teste", "-d", "todolist"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: on-failure

  web:
    build: ./web
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api
